// SONGS
export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_EMPTY = 'FETCH_SONGS_EMPTY';

// PLAYER
export const PLAY_SONG = 'PLAY_SONG';
export const ON_PLAY = 'ON_PLAY';
export const ON_PAUSE = 'ON_PAUSE';
export const ON_TOGGLE_REPEAT = 'ON_TOGGLE_REPEAT';
export const ON_TOGGLE_SHUFFLE = 'ON_TOGGLE_SHUFFLE';
export const ON_LOAD_START = 'ON_LOAD_START';
export const ON_LOADED_METADATA = 'ON_LOADED_METADATA';
export const ON_TIME_UPDATE = 'ON_TIME_UPDATE';
export const ON_VOLUME_CHANGE = 'ON_VOLUME_CHANGE';

// NAV
export const ON_SONGS_SEARCH = 'ON_SONGS_SEARCH';

// HISTORY
export const ON_TOGGLE_SHOW_HISTORY = 'ON_TOGGLE_SHOW_HISTORY';
